# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  -   id: trailing-whitespace
  -   id: end-of-file-fixer
  -   id: check-yaml
  -   id: check-added-large-files
# isort should run before black as black sometimes tweaks the isort output
- repo: https://github.com/PyCQA/isort
  rev: 5.9.3
  hooks:
    - id: isort
      exclude: ^(Download/|Postprocess/|Preprocess/|main.py)
# https://github.com/python/black#version-control-integration
- repo: https://github.com/psf/black
  rev: 21.8b0
  hooks:
    - id: black
      exclude: ^(Download/|Postprocess/|Preprocess/|main.py)
- repo: https://github.com/keewis/blackdoc
  rev: v0.3.4
  hooks:
    - id: blackdoc
      exclude: ^(Download/|Postprocess/|Preprocess/|main.py)
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      exclude: ^(Download/|Postprocess/|Preprocess/|main.py)
