channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.5
  - cython
  - pyhdf>=0.10.1
  - pip
  - rioxarray  # this should be in separate dependency only if people want to use data from modaps
